
name: Lyouoa

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip python -m piptools compile -o requirements.txt pyproject.toml
        pip install -r requirements.txt
    - name: cat requirements
      run: |
        cat requirements.txt
    - name: pyinstaller build
      run: |
        pyinstaller lyouoa.py
        ls dist/lyouoa
