
name: Lyouoa

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        #platform: [macos-latest, Ubuntu-latest, windows-latest]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version-file: '.python-version' 
    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install -r requirements.lock
    - name: pyinstaller build
      run: |
        pyinstaller lyouoa.py
        ls dist/lyouoa
    - name: upload to release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: dist/lyouoa/lyouoa.exe
        tags: false
        draft: true
